{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "6abce94f-5f21-41f1-b50c-e9423f9f6e4e",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-07-24 09:52:21.468 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-24 09:52:21.469 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-24 09:52:21.953 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\ProgramData\\anaconda3\\Lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n",
      "2025-07-24 09:52:21.953 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-24 09:52:21.954 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-24 09:52:21.955 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-24 09:52:21.955 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-24 09:52:21.956 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-24 09:52:21.956 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-24 09:52:21.957 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-24 09:52:21.958 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-24 09:52:21.959 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-24 09:52:21.960 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-24 09:52:21.960 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-24 09:52:21.962 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-24 09:52:21.962 Session state does not function when running a script without `streamlit run`\n",
      "2025-07-24 09:52:21.963 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-24 09:52:21.963 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-24 09:52:21.964 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-24 09:52:21.964 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-24 09:52:21.965 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-24 09:52:21.965 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-24 09:52:21.966 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-24 09:52:21.967 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-24 09:52:21.968 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-24 09:52:21.968 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-24 09:52:21.969 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-24 09:52:21.969 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-24 09:52:21.969 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-24 09:52:21.970 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-24 09:52:21.970 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-24 09:52:21.971 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-24 09:52:21.971 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-24 09:52:21.971 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-24 09:52:21.971 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-24 09:52:21.972 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-24 09:52:21.972 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-24 09:52:21.973 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-24 09:52:21.973 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-24 09:52:21.974 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-24 09:52:21.976 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-24 09:52:21.977 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-24 09:52:21.977 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-24 09:52:21.978 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-24 09:52:21.979 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-24 09:52:21.979 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-24 09:52:21.980 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-24 09:52:21.981 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-24 09:52:21.981 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-24 09:52:21.981 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-24 09:52:21.982 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-24 09:52:21.983 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-24 09:52:21.983 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-24 09:52:21.984 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-24 09:52:21.984 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-24 09:52:21.985 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import pickle\n",
    "\n",
    "# === Load the trained model ===\n",
    "with open(\"RandomForest_HHO_model.pkl\", \"rb\") as file:\n",
    "    model_loaded = pickle.load(file)\n",
    "\n",
    "st.set_page_config(page_title=\"Embedment Depth Prediction\", layout=\"centered\")\n",
    "\n",
    "# === Title ===\n",
    "st.title(\"Embedment Depth Prediction using Hybrid RF-HHO Model\")\n",
    "st.markdown(\"### Prediction of Embedment Depth of Sheet Pile (D)\")\n",
    "\n",
    "# === Input Fields ===\n",
    "st.subheader(\"Enter Soil Properties\")\n",
    "\n",
    "# Display labels for UI\n",
    "display_labels = {\n",
    "    'gamma1': 'γ₁ (kN/m³)',\n",
    "    'phi1': 'φ₁ (°)',\n",
    "    'gamma2': 'γ₂ (kN/m³)',\n",
    "    'C2': 'C₂ (kPa)'\n",
    "}\n",
    "\n",
    "# Mapping for model input\n",
    "feature_mapping = {\n",
    "    'gamma1': 'g1',\n",
    "    'phi1': 'phi1',\n",
    "    'gamma2': 'g2',\n",
    "    'C2': 'C2'\n",
    "}\n",
    "\n",
    "# Create input fields\n",
    "input_data = {}\n",
    "for var, label in display_labels.items():\n",
    "    input_data[feature_mapping[var]] = st.number_input(label, value=0.0, format=\"%.2f\")\n",
    "\n",
    "# === Predict Button ===\n",
    "if st.button(\"Predict\"):\n",
    "    df_input = pd.DataFrame([input_data])\n",
    "    prediction = model_loaded.predict(df_input)\n",
    "    pred_val = round(prediction[0], 3)\n",
    "    st.success(f\"Predicted Depth (D): {pred_val} m\")\n",
    "\n",
    "    # Store session state for export\n",
    "    st.session_state['latest_prediction'] = (input_data, pred_val)\n",
    "\n",
    "# === Clear Button ===\n",
    "if st.button(\"Clear\"):\n",
    "    for key in feature_mapping.values():\n",
    "        input_data[key] = 0.0\n",
    "    st.experimental_rerun()\n",
    "\n",
    "# === Export Button ===\n",
    "if 'latest_prediction' in st.session_state:\n",
    "    input_values, pred_val = st.session_state['latest_prediction']\n",
    "    df_export = pd.DataFrame([list(input_values.values()) + [pred_val]],\n",
    "                             columns=list(input_values.keys()) + ['D'])\n",
    "\n",
    "    csv = df_export.to_csv(index=False).encode('utf-8')\n",
    "    st.download_button(label=\"Download Prediction as CSV\",\n",
    "                       data=csv,\n",
    "                       file_name='prediction_output.csv',\n",
    "                       mime='text/csv')\n",
    "else:\n",
    "    st.info(\"Make a prediction to enable CSV export.\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8bb3bec7-f832-4594-a7c5-edf578793fa7",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
